name = "telegram-thai"
compatibility_date = "2026-02-12"
compatibility_flags = ["nodejs_compat"]
account_id = "9124272a5c3e327f2e943bf27c0910c4"

[assets]
directory = "docs/.vuepress/dist"

[placement]
mode = "smart"


